resource_group_name    = "kv_rbac_terraform_rg"
location               = "westeurope"
keyvault_name          = "keyvaultrbac2022"
secret_name            = "DatabasePassword"
secret_value           = "@Aa123456789!"